<project>
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>com.cavetale.pom</groupId>
    <artifactId>cavetale-pom-base</artifactId>
    <version>0.1-SNAPSHOT</version>
  </parent>

  <groupId>com.winthier.toomanyentities</groupId>
  <artifactId>toomanyentities</artifactId>
  <version>0.1</version>

  <name>TooManyEntities</name>
  <url>http://www.winthier.com</url>
  <packaging>jar</packaging>

  <dependencies>

    <!-- Paper API -->
    <dependency>
      <groupId>io.papermc.paper</groupId>
      <artifactId>paper-api</artifactId>
    </dependency>

    <!-- Lombok -->
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <scope>provided</scope>
    </dependency>

    <!-- Core -->
    <dependency>
      <groupId>com.cavetale.core</groupId>
      <artifactId>core</artifactId>
      <version>0.1-SNAPSHOT</version>
      <scope>provided</scope>
    </dependency>

  </dependencies>
</project>
